### ISSUE TITLE
ABHD2 Open Online Meeting - Tue Oct 18th

### ISSUE THREAD

**Issue by mattodd** [StructuralGenomicsConsortium/CNP6-ABHD2#2]
**Date**: Oct 18th 2022
**Time**: 1pm UK time ([other times](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=10&day=18&hour=12&min=0&sec=0&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=196&p10=240))  
**Place**: https://ucl.zoom.us/j/93595179967  
**Recording**:  https://youtu.be/-lqmnAvZAE8
**Previous Meeting**: none
**Who can come?**: Anyone. No need to say anything unless you'd like to. If you'd like to contribute, please join Github.

_Apologies_: 

_Decks_: Please @StructuralGenomicsConsortium/cnp6-abhd2 remember that if you share slides/info, to drag and drop those into a comment on this page, below. _Very easy and saves @mattodd having to pester you._

**Agenda**:

### 1) Protein Production

Update from @OliverArnolds.

### 2) Chemical Ordering and Synthesis

Update to what's been discussed in #1. @Evert-Homan @EveCarter @MartinHaraldsson 

### 3) AOB

Does anyone else need to be invited to these meetings to grow the group productively?

**Next Meeting**
Nov 15th 4pm UK time.

**L'esprit de l'escalier**
If you'd like to follow up after the meeting, please comment below. You can also email, but please be clear if anything in the email should not be public domain - the default is open.

**Comment by mattodd** [comment]
Hi @EveCarter - are you OK to take brief notes in the meeting today and post anything important, and assign any actions? Can use the little checkbox, like this:

- [ ] @EveCarter to assign actions

 I will record and post the meeting to YouTube as soon as I can and install the link above.

**Comment by OliverArnolds** [comment]
Hi all, thanks for the meeting! Here my slides:
[SGC_ABHD2-open_221018.pptx](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/files/9810612/SGC_ABHD2-open_221018.pptx)

**Comment by EveCarter** [comment]
A brief summary of this meeting:
- Madison in Toronto has soluble ABHD2 protein fused with an MBP tag. After cleavage of the tag, only a small amount of protein is soluble in mild detergent.
- Oliver will test for activity of the fused protein and Madison will continue work on cleavage approaches.
- Evert, Kirsty and Pauline have synthesised/purchased a range of structures ([issue #1](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/issues/1))  based on the original inhibitor from the [2019 paper](https://pubs.acs.org/doi/10.1021/acschembio.9b00640). Evert has also ordered some known inhibitors of ABHD6 and ABHD12.
- Once Oliver has active protein, he will assay these with ABHD2 and compare to the other ABHDs if possible.

**Comment by mattodd** [comment]
Evert sent slides by email

[ABHD2i_chemistry_evehom_221018.pptx](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/files/9820291/ABHD2i_chemistry_evehom_221018.pptx)

also uploaded [here](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/tree/main/File%20Diary/2022/October%20Online%20Meeting).

**Comment by MFernflower** [comment]
@mattodd this is just random speculation but if a decent stock of the "Known Literature Inhibitor" exists it would be cool to send a few mg over to Wendy to screen vs Mycetoma - the tricyclic ureas are pretty novel looking and who knows what they could do

**Comment by ghost** [comment]
Who is Wendy?

**Comment by mattodd** [comment]
@Evert-Homan Wendy is the biologist leading an unrelated project on drug discovery for mycetoma, MycetOS.
@MFernflower (you see the importance of providing context if you're in a room of strangers :) ). Cross-screening is an excellent idea, but always takes time to organise. I recommend we wait till we have a stock of molecules and then ship a selection all together. But thanks for the reminder.

**Comment by jsmowat** [comment]
As a follow-up to our discussion, I wanted to make everyone aware of a recent patent from ONO Pharmaceutical on ABHD6 inhibitors (WO2022211060 - https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2022211060). I only had a brief scan so far of the patent (its in Japanese), but I think there are some interesting details around assays that we should look into further. They seem to have that similar amide linkage we have seen in other ABHD literature compounds. Once a deep dive of the patent is completed, we can decide if it might make sense to synthesize a tool compound from this patent and check for selectivity, as this could provide other potential starting points.

**Comment by mattodd** [comment]
That's great, @jsmowat, thanks for spotting and flagging, definitely need to digest this.
