### ISSUE TITLE
ABHD2 Open Online Meeting - Tue Feb 14th

### ISSUE THREAD

**Issue by EveCarter** [StructuralGenomicsConsortium/CNP6-ABHD2#4]
**Date**: Tues Feb 14th 2023
**Time**: 4pm UK time ([other times](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=2&day=14&hour=16&min=0&sec=0&p1=43&p2=136&p3=37&p4=239&p5=250&p6=240&p7=770))
**Place**: [https://ucl.zoom.us/j/93559157118](https://ucl.zoom.us/j/93559157118?pwd=SnpIaEFIbW9UN2UzTFV5dG1KRGY3UT09)
**Recording**:  [YouTube link](https://www.youtube.com/watch?v=eyMzcXxOnwg&list=PL0eLxnHhou_k8BLh9IBYONsRwRcgtVykq&index=8)
**Previous Meeting**: issue #3 
**Who can come?**: Anyone. No need to say anything unless you'd like to. If you'd like to contribute, please join Github.

_Present_: Dr Oliver Arnolds (Karolinska Institut), Professor Matthew Todd (UCL), Dr Eve Carter (UCL), Dr Madison Edwards (Uni of Toronto), Aiden Pidd (Uni of Manchester), Dr Jeffrey Mowat (Janssen Pharmaceutica NV), Professor Opher Gileadi (Karolinska Institut), Dr Evert Homan (SciLifeLab), Chelsey Brien (Uni of Toronto), Vincent Trudel (Uni of Toronto).

_Decks_: Please @StructuralGenomicsConsortium/cnp6-abhd2 remember that if you share slides/info, to drag and drop those into a comment on this page, below. _Very easy and saves @mattodd having to pester you._

### 1) Protein Production

Update from @OliverArnolds and Madison Edwards on protein production of ABHD2.
**In meeting**: SGC Toronto have been trying to express ABHD2 in baculovirus, but only got a very small amount of soluble protein. Protein was ordered from Genscript using TurboCHO; it is thought this protein got produced but oxidised and was not secreted. Oliver and Opher have designed four constructs using [PROSS](https://pross.weizmann.ac.il/step/pross-terms/), with test expressions ongoing. Commercial ABHD2 from Origene is thought to be inactive from an assay with p-nitrophenyl octanoate.

- [x] Oliver to perform test expression of PROSS constructs.
- [x] Test full length ABHD2 production in mammalian cells.

### 2) Screening of Potential Inhibitors

Update from @OliverArnolds (some potential inhibitors discussed in issue #1). 
**In meeting**: Oliver gave a summary of boryl and UNC compounds which have been tested with ABHD10 for inhibition. 

- [x] Eve to synthesise analogues of boryl inhibitors.

### 3) Crystallisation

Update from @OliverArnolds on protein crystallisation including co-crystallisation.
**In meeting**: Oliver has crystallised UNC0200 and VT8-27 with ABHD10. So far, there are no clear densities for the ligands.

- [x] Oliver will continue looking at results.

**Next Meeting**: 14th March 2023, 4pm UK time

**L'esprit de l'escalier**
If you'd like to follow up after the meeting, please comment below. You can also email, but please be clear if anything in the email should not be public domain - the default is open.

**Comment by OliverArnolds** [comment]
Here my slides from the meeting:
[SGC_ABHD2-open_230214.pptx](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/files/10988463/SGC_ABHD2-open_230214.pptx)

**Comment by ghost** [comment]
Thanks. All quiet on the x-ray front?

Are you coming to the SciLife pub today? St. Patricks day with pub quiz!

Cheers/E
