### ISSUE TITLE
ABHD2 Open Online Meeting - Tue Mar 14th

### ISSUE THREAD

**Issue by EveCarter** [StructuralGenomicsConsortium/CNP6-ABHD2#5]
**Date**: Tues Mar 14th 2023
**Time**: 4pm UK time ([other times](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=3&day=14&hour=16&min=0&sec=0&p1=239&p2=136&p3=37&p4=250&p5=224&p6=240))
**Place**: [zoom link](https://ucl.zoom.us/j/93660573410?pwd=dzdGMnBQVi9kQmZCaTU0TFg5K2RlQT09)
**Recording**:  
**Previous Meeting**: issue #4 
**Who can come?**: Anyone. No need to say anything unless you'd like to. If you'd like to contribute, please join Github.

_Present_: 

_Decks_: Please @StructuralGenomicsConsortium/cnp6-abhd2 remember that if you share slides/info, to drag and drop those into a comment on this page, below. _Very easy and saves @mattodd having to pester you._

### 1) Protein Production

**In meeting:** Oliver has designed 6 constructs using [PROSS](https://pross.weizmann.ac.il/step/pross-terms/): four C-terminal His and Avi tagged constructs (WT and 3 from PROSS), two N-terminal His-tagged (WT and most mutated from PROSS) and two for mammalian cells. He tested the _E. coli_ constructs in SHuffle cells as these should be good for cysteine rich proteins, such as ABHD2. On a small scale, these expressed decently but did not purify well. On a larger scale, it appears that the protein aggregates, based on the retention time of size exclusion chromatography (SEC). This aggregated protein was found to be active from an assay with p-nitrophenyl butyrate and activity was found to decrease when the protein was incubated with a published ABHD2 inhibitor.

In Toronto, Madison has successfully expressed His-FLAG-ABHD2(33-425) in _E. coli_. Purification with Nickel beads then SEC gave mostly clean protein corresponding to monomers. Protein expression was confirmed by mass spectrometry and activity was confirmed with the p-nitrophenyl butyrate assay. The yield was low, only 0.45 mg from 11 L, but these are promising results.

Oliver tried to replicate Madison's conditions in Stockholm. Expression was decent, although protein was found to be aggregated based on the retention time on SEC. As before, activity was still seen in the p-nitrophenyl butyrate assay and activity was found to decrease when the protein was incubated with a published ABHD2 inhibitor.

**Next Meeting**:
Tuesday 18th April, 3pm UK time.

**L'esprit de l'escalier**
If you'd like to follow up after the meeting, please comment below. You can also email, but please be clear if anything in the email should not be public domain - the default is open.

**Comment by OliverArnolds** [comment]
Hi all! Here my slides. Thank you for the meeting and looking forward to the next one!
[SGC_ABHD2-open_230314.pptx](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/files/10988397/SGC_ABHD2-open_230314.pptx)
