### ISSUE TITLE
Synthesis of enantiomers of TH14125

### ISSUE THREAD

**Issue by ghost** [StructuralGenomicsConsortium/CNP6-ABHD2#7]
@EveCarter Since racemic TH14125 stabilized the melting point of purified ABHD2 with almost 5 degrees it was suggested at the ABHD2 Update on 2023-04-24 to get our hands on the enantiomers. I believe you can buy both enantiomers of 2-benzylpiperidine:

https://www.molport.com/shop/moleculelink/ITXCORRITGNIHP-GFCCVEGCSA-N/35943083?searchkey=5LEKDGEOQA0QH1GUUPRD99&searchtype=chemical-search

https://www.molport.com/shop/moleculelink/ITXCORRITGNIHP-LBPRGKRZSA-N/35943084?searchkey=5LEKDGEOQA0QH1GUUPRD99&searchtype=chemical-search

These should be compatible with the synthetic route that was used to make the racemate. Eve, is this something you could take on?

Best wishes/Evert

**Comment by EveCarter** [comment]
Closing as this work has been completed. Linked in the wiki.
