### ISSUE TITLE
ABHD2 Open Online Meeting - Tue June 27th

### ISSUE THREAD

**Issue by EveCarter** [StructuralGenomicsConsortium/CNP6-ABHD2#9]
**Date**: Tuesday June 27th 2023
**Time**: 4pm UK time ([other times](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=6&day=27&hour=15&min=0&sec=0&p1=239&p2=136&p3=37&p4=250&p5=224&p6=240))
**Place**: [zoom link](https://ucl.zoom.us/j/94178801414?pwd=M2l6MW12UkJzREQveVRKbHZrRjdSdz09)
**Recording**:  
**Previous Meeting**: issue #8 
**Who can come?**: Anyone. No need to say anything unless you'd like to. If you'd like to contribute, please join Github.

_Present_: Dr Oliver Arnolds (Karolinska Institut), Dr Eve Carter (UCL), Dr Evert Homan (SciLifeLab), Dr Jeffrey Mowat (Janssen Pharmaceutica NV), Dr Madison Edwards (Uni of Toronto).

_Decks_: Please remember that if you share slides/info, to drag and drop those into a comment on this page, below. _Very easy and saves @mattodd having to pester you._

### Agenda:

@OliverArnolds to update on expression of ABHD2 and screening of inhibitors.

**In meeting:** Oliver has partially digested the protein to remove the N-terminal tag, with the idea that removing this flexible region could increase the quality of crystals. He has done this with a dilute amount of Trypsin/Chymotrypsin. Currently there are no crystals. 

Oliver has screened some boryl compounds from Andrei Yudin (Uni of Toronto) that have previously been screened against ABHD10 (issue #4). Three appear to give decent inhibition (>50%) in an assay with p-nitrophenyl butyrate. 

NanoDSF of racemic and single enatiomeric TH14125 (synthesised by Eve) gave similar results. It was discovered that the original sample of TH14125 was actually 100 mM rather than 10 mM therefore all measurements of this are out. Dose-response curves with p-nitrophenyl butyrate are also similar.

Oliver has assayed the 53 compounds from issue #1, with three structures and TH14125 appearing to give the best results. He has measured IC50s of these four, with the best giving an IC50 of 26 nM. 

- [x] Oliver to measure IC50s of all compounds giving inhibition of >50%.
- [x] Oliver to perform nanoDSF and SPR as an orthogonal assay.

**L'esprit de l'escalier**
If you'd like to follow up after the meeting, please comment below. You can also email, but please be clear if anything in the email should not be public domain - the default is open.

**Comment by mattodd** [comment]
Really sorry @StructuralGenomicsConsortium/cnp6-abhd2 but I'm an apology today since I'm at a funding event, but:
1) It's fantastic that we are now getting reliable inhibition data vs protein.
2) Also fantastic that we've data suggesting good levels of inhibition, but
3) I think we're going to need a bunch more IC50s in order to be able to glean trends. We need to be clear who can. or is willing to, do this work - KI or UCL?
Either way, really exciting.

**Comment by ghost** [comment]
@jsmowat Here's the ABHD6 background data on CBK600218:

https://www.probes-drugs.org/compounds/standardized#attribute=30997@AND
